admin_index:
  path:     /admin/index
  defaults: { _controller: AdminBundle:Admin:index }

admin_panel:
  path:     /admin/panel
  defaults: { _controller: AdminBundle:Admin:panel }

admin_posts:
  path:     /admin/posts
  defaults: { _controller: AdminBundle:Admin:posts }

admin_post:
    path:     /admin/post
    defaults: { _controller: AdminBundle:Admin:post }

admin_post_types:
    path:     /admin/post_types
    defaults: { _controller: AdminBundle:Admin:postTypes }

admin_add_post_type:
    path:     /admin/post_type/add
    defaults: { _controller: AdminBundle:Admin:addPostType }

admin_delete_post_type:
    path:     /admin/post_type/delete/{id}
    defaults: { _controller: AdminBundle:Admin:deletePostType }
    requirements:
        id: '\d+'

admin_edit_post_type:
    path:     /admin/post_type/edit/{id}
    defaults: { _controller: AdminBundle:Admin:editPostType }
    requirements:
        id: '\d+'

admin_add_taxonomy:
    path:     /admin/taxonomy/add
    defaults: { _controller: AdminBundle:Admin:addTaxonomy }

admin_taxonomies:
    path:     /admin/taxonomies
    defaults: { _controller: AdminBundle:Admin:taxonomies }

admin_delete_taxonomy:
    path:     /admin/taxonomy/delete/{id}
    defaults: { _controller: AdminBundle:Admin:deleteTaxonomy }
    requirements:
        id: '\d+'

admin_edit_taxonomy:
    path:     /admin/taxonomy/edit/{id}
    defaults: { _controller: AdminBundle:Admin:editTaxonomy }
    requirements:
        id: '\d+'

admin_users:
    path:     /admin/users
    defaults: { _controller: AdminBundle:Admin:users }

admin_delete_user:
    path:     /admin/user/delete/{id}
    defaults: { _controller: AdminBundle:Admin:deleteUser }
    requirements:
        id: '\d+'

admin_add_user:
    path:     /admin/user/add
    defaults: { _controller: AdminBundle:Admin:addUser }

admin_add_post:
    path:     /admin/post/add/{id}
    defaults: { _controller: AdminBundle:Admin:addPost }
    requirements:
        id: '\d+'