services:
    admin.taxonomy_helper:
        class: AdminBundle\Helper\TaxonomyHelper
        arguments: ['@doctrine.orm.entity_manager']

    admin.post_helper:
        class: AdminBundle\Helper\PostHelper
        arguments: ['@doctrine.orm.entity_manager']

    admin.type.entity_hidden:
        class: AdminBundle\Form\Type\EntityHiddenType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
        - { name: form.type }