fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

auth_bundle:
    resource: "@AuthBundle/Resources/config/routes.yml"

admin_bundle:
    resource: "@AdminBundle/Resources/config/routes.yml"