AdminBundle\Entity\ContentType:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\ContentTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '20'
        slug:
            type: string
            length: '20'
        description:
            type: string
            length: 150
    lifecycleCallbacks: {  }
