AdminBundle\Entity\Taxonomy:
    type: entity
    table: null
    repositoryClass: AdminBundle\Repository\TaxonomyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '20'
        slug:
            type: string
            length: '20'
        parent:
            type: integer
    lifecycleCallbacks: {  }
